version: "3.8"
services:
  gw-test:
    environment:
      - "OOAPI_MOCK_URL=http://ooapi-mock:8080/"
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    links:
      - ooapi-mock
  ooapi-mock:
    image: "jlmr/ooapi-mock:latest"
    ports:
      - "8081:8080"
