version: "3.8"
services:
  gw-test:
    environment:
      - "OOAPI_TEST_BACKEND_URL=http://test-backend/"
      - "OOAPI_OTHER_TEST_BACKEND_URL=http://test-backend2/"
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
      - "4444:4444"
    links:
      - test-backend
  test-backend:
    build:
      context: test-backend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
  test-backend2:
    build:
      context: test-backend
      dockerfile: Dockerfile
      args:
        WWW_DATA_DIR: data2/
        SITE_CONFIG: default.with-basic-auth
    ports:
      - "8083:80"
