version: "3.8"
services:
  gw-test:
    environment:
      - "OOAPI_TEST_BACKEND_URL=http://test-backend/"
      - "DEBUG=express-openapi-validate"
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    links:
      - test-backend
  test-backend:
    build:
      context: test-backend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
