# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: codelab
    foo: bar

#rule_files:
#  - "first.rules"
#  - "my/*.rules"

scrape_configs:
  - job_name: scrape-static

    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scheme: http

    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: prometheus
      - targets: ["gateway:8080"]
        labels:
          service: ooapi-gateway

