# Core
db:
  redis:
    namespace: '${REDIS_NAMESPACE:-EG}'
    host: '${REDIS_HOST:-redis}'
    port: '${REDIS_PORT:-6379}'
    username: '${REDIS_USERNAME}'
    password: '${REDIS_PASSWORD}'

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config'

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10
