# Core
db:
  redis:
    namespace: '${REDIS_NAMESPACE:-EG}'
    host: '${REDIS_HOST:-redis}'
    port: '${REDIS_PORT:-6379}'

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config'

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10
